### ISSUE TITLE
[Feat]시각화 페이지 도움 완료 api 연결

### ISSUE THREAD

**Issue by seroak** [edu-pi/Front#161]
## 📝 Description
**무엇을?**
- 시각화 페이지에서 학생이 선생님에게 도움 완료 요청을 보낼 수 있는 버튼 생성

**왜?**
- 학생이 도움 완료 요청을 보내기 위해

## ❗️Todo
- [x] 시각화 페이지 클래스룸 용으로 새로 만들기
- [x] 도움 요청 버튼 만들기
- [x] 도움 요청 api 만들기

## ETC
기타사항
