### ISSUE TITLE
[Feat] 시각화 페이지 위에 버튼 위치 조정

### ISSUE THREAD

**Issue by seroak** [edu-pi/Front#195]
## 📝 Description
**무엇을?**
- 시각화 페이지 버튼 위치 변경
![image](https://github.com/user-attachments/assets/854f3c6d-ca56-4a9a-9506-81d1fbf2e33d)

**왜?**
- 버튼이 차지하는 공간을 최대한 줄여서 시각화를 더 보여주기 위해

## ❗️Todo
- [ ] 실행코드 버튼 위치 변경 
- [ ] 옵션추가 버튼 생성
- [ ] 시각화 버튼과 시각화 조절 버튼 위치 변경

## ETC
기타사항
