### ISSUE TITLE
[Feat] 에러나는 기능 수정

### ISSUE THREAD

**Issue by seroak** [edu-pi/Front#204]
## 📝 Description
**무엇을?**
- 클래스룸 부분에서 발생하는 에러 고치기
- 클래스룸 상태관리 UseQuery하고 zustand로 관리
- 시각화부분 진행 하이라이트 기능 추가
- 코드 실행 기능 추가
- gpt 수정 기능 에러 수정

**왜?**
- 에러가 나는 기능을 고치기 위해

## ❗️Todo
- [x] 클래스룸 권환으로 보여지는거 달라지게 구현
- [x] 시각화부분 진행 하이라이트 기능 추가
- [x] 클래스룸 상태관리 UseQuery하고 zustand로 관리
- [x] 코드 실행 기능 추가
- [x] gpt 수정 기능 에러 수정
## ETC
기타사항
