### ISSUE TITLE
[Feat]코드 실행버그 해결

### ISSUE THREAD

**Issue by seroak** [edu-pi/Front#209]
## 📝 Description
**무엇을?**
- 코드 실행할때 일어나는 버그 수정
- 클래스룸 페이지 학생 상태정보 표시 에러 해결
**왜?**
- 코드 시각화를 할때 일어나는 버그를 수정하기 위해서

## ❗️Todo
- [x] arg에서 일어나는 버그 수정
- [x] 클래스룸 페이지 학생 상태정보 표시 에러 해결
- [x] variable 자료구조 시각화 css 정렬

## ETC
기타사항
