### ISSUE TITLE
[Feat] 배포시 console.log 삭제, 클래스 생성 에러 처리, 시각화 코드 실행 버튼 에러 수정, 회원가입 페이지 모두 선택 버튼 기능 추가

### ISSUE THREAD

**Issue by seroak** [edu-pi/Front#216]
## 📝 Description
**무엇을?**
- 배포시 console.log 안찍히게 변경
- 클래스 생성 에러 처리
- 시각화 누르고 코드 실행 가능하게 하기
- 회원가입 페이지 모두선택기능 만들기

**왜?**
- 사용자에게 console.log가 안찍히게 만들기 위해

## ❗️Todo
- [x]  배포시 console.log 삭제
- [x] 클래스 생성 에러 처리
- [x] 시각화 누르고 코드 실행 가능하게 하기
- [x] 회원가입 페이지 모두선택기능 만들기

## ETC
기타사항
